volumes:
  pg_data:
  static:

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  todo_list:
    build: ./todo_list/
    env_file: .env
    volumes:
      - static:/backend_static
    ports:
      - 8000:8000
    depends_on:
      - db

  fast_api:
    env_file: .env
    build: ./fast_api/
    ports:
      - 8080:8080
    depends_on:
      - db
      - todo_list
      - redis

  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
    ports:
      - 80:80
    depends_on:
      - db
      - todo_list
      - fast_api
