# Generated by Django 3.2.16 on 2024-09-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('completion_date',), 'verbose_name': 'задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
